[tool.briefcase]
project_name = "bincode"
bundle = "io.github.tusharhero"
version = "0.0.1"
url = "https://tusharhero.github.io/bincode/gui"
license = "MIT license"
author = 'Tushar Maharana'
author_email = "tusharmaharana44676@gmail.com"

[tool.briefcase.app.bincode-app]
formal_name = "bincode-app"
description = "A gui for bincode, (like QR-code)"
icon = "src/bincode_app/resources/bincode-app"
sources = ['src/bincode_app']
requires = [
]


[tool.briefcase.app.bincode-app.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.bincode-app.linux]
requires = [
    'toga-gtk>=0.3.0.dev32',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.bincode-app.windows]
requires = [
    'toga-winforms>=0.3.0.dev32',
]

# Mobile deployments
[tool.briefcase.app.bincode-app.iOS]
requires = [
    'toga-iOS>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.bincode-app.android]
requires = [
    'toga-android>=0.3.0.dev32'
]
